spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javakc?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
#    数据库脚本数据初始化
#    schema: classpath:db/system_ddl.sql
#    data: classpath:db/system_dml.sql
#    initialization-mode: always

  #    -------------Jackson Start---------------
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
#    -------------Jackson End---------------

#    -------------Redis Start---------------
  redis:
#    -------------单机节点---------------
#    host: 127.0.0.1
#    port: 6379
#    database: 0
#    -------------哨兵模式---------------
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:16379,127.0.0.1:16380,127.0.0.1:16381
#    -------------Redis End---------------

#    -------------Redis Token Start---------------
token:
  tokenHead: 'Bearer '
  tokenHeader: Authorization
  redisToken: 'user:token:'
#    -------------Redis Token End---------------